### ISSUE TITLE
Only 25 session cap for each scrapbook!

### ISSUE THREAD

**Issue by maxwofford** [hackclub/hack-hour#101]
Must #scrapbook at least once every 25 hours! If you're scrapbooking more hours then that it probably means people aren't shipping quick and shipping often.

**Comment by techpixel** [comment]
solved

**Comment by techpixel** [comment]
<img width="558" alt="image" src="https://github.com/hackclub/hack-hour/assets/68567672/f829b5dc-7c82-4625-9005-18207dc1741e">
