### ISSUE TITLE
Sessions should be attached to a scrapbook in order

### ISSUE THREAD

**Issue by maxwofford** [hackclub/hack-hour#107]
<img width="587" alt="Screenshot 2024-07-03 at 10 18 32" src="https://github.com/hackclub/hack-hour/assets/5891442/1d943c59-3207-41c5-bd7d-a2e62c2a9ad4">

Currently sessions are associated with scrapbooks in airtable with a random order (I suspect it's the order they were selected in slack at the "select the sessions you want to scrapbook" step). We should sort those by creation date to make sure that sessions are in order.

**Comment by techpixel** [comment]
the bot now sorts sessions in the scrapbook reviewer flow!
