### ISSUE TITLE
Don't protect from replies to threads in #arcade-shoutouts

### ISSUE THREAD

**Issue by maxwofford** [hackclub/hack-hour#112]
<img width="511" alt="Screenshot 2024-07-05 at 13 10 02" src="https://github.com/hackclub/hack-hour/assets/5891442/02698a6a-4b3a-4f93-9145-79ad095c4ad0">
https://hackclub.slack.com/archives/C07AQ75CWQJ/p1720195848014859?thread_ts=1720195733.393839&cid=C07AQ75CWQJ

**Comment by taciturnaxolotl** [comment]
want me to fix this?

**Comment by maxwofford** [comment]
@kcoderhtml yeah, submit a PR!

**Comment by taciturnaxolotl** [comment]
On it!

**Comment by techpixel** [comment]
completed
