### ISSUE TITLE
Please add README file

### ISSUE THREAD

**Issue by FahadLive** [hackclub/hack-hour#28]
Adding a README file/intro on how things in the project is laid would help others to help/engage in the codebase.

**Comment by techpixel** [comment]
I'll do this soon! For now, feel free to reach out to me on slack at @manitej so I can teach you more about how things work under the hood

**Comment by maxwofford** [comment]
@Ranger-NF are you up to work on your own pass of this?

**Comment by FahadLive** [comment]
I haven't had the time to reach out to @techpixel to learn about the repo, but the README file looks up to mark for a new comer to understand the code base. Good job guys!

PS: Now I'm curious to learn more about this repo.. Haha
