### ISSUE TITLE
link to hack-hour thread on running /arcade

### ISSUE THREAD

**Issue by maxwofford** [hackclub/hack-hour#49]

**Comment by jaspermayone** [comment]
![CleanShot 2024-06-17 at 16 23 43@2x](https://github.com/hackclub/hack-hour/assets/65788728/530692d6-be7e-4655-b71a-d8d582ef5823)

**Comment by jaspermayone** [comment]
See thread at https://hackclub.slack.com/archives/C07897CNC4D/p1718655636185379

**Comment by techpixel** [comment]
already added!

**Comment by techpixel** [comment]
<img width="783" alt="image" src="https://github.com/hackclub/hack-hour/assets/68567672/f70ddcd8-b78d-4af1-bdaf-f66960afa098">
