### ISSUE TITLE
Add "..." to truncated goal message

### ISSUE THREAD

**Issue by maxwofford** [hackclub/hack-hour#57]
![image (39)](https://github.com/hackclub/hack-hour/assets/5891442/e1c37321-6657-46e5-ad07-f1d3d7e88f3c)

**Comment by TheScientist101** [comment]
https://github.com/hackclub/hack-hour/pull/58
I created a PR fixing this issue, I think. I am unable to test it without deploying the bot to a Slack server.

**Comment by techpixel** [comment]
Solved with #64
