### ISSUE TITLE
commit link vs repo link

### ISSUE THREAD

**Issue by maxwofford** [hackclub/hack-hour#60]
currently when we detect if a 'scrap' has been posted we check for github.com/user/repo links– that shouldn't count the same way a specific commit link counts b/c users are spending 5 sessions & all link "github.com/user/repo", which means I can only approve 1 of the hours

**Comment by techpixel** [comment]
so far I've been checking any link 🙈 - but david has the logic to detect git commits, I'll take a look at his code & replace the current logic
