### ISSUE TITLE
`/api/clock/:slackId` returns incorrect time for sessions with pauses

### ISSUE THREAD

**Issue by samdev-7** [hackclub/hack-hour#74]
The endpoint /api/clock/:slackId considers the start time + duration as the end time and ignores pauses in the session. [Relavent code](https://github.com/hackclub/hack-hour/blob/8718e98157b4ba78735d937b97b0704471c18855/src/extensions/api/index.ts#L60-L61)

This results in lower than actual values being returned, sometimes into the negatives, for sessions that have previously been paused.

**Comment by techpixel** [comment]
Solved with new `/api/session/:slackId` endpoint in #76. The old `/api/clock/:slackId` endpoint is depreciated.
